# Generated by Django 3.2 on 2021-04-15 11:14

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=128)),
                ('permission_code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'Username already exists'}, help_text='Username is required. Fewer than 256 character', max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.CharField(max_length=320, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin permisson')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('join_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='join at')),
                ('permissions', models.ManyToManyField(db_table='account_permissions', related_name='account', to='accounts.Permission')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
